---
title: "CareCoord_staff"
author: "Esther Lips"
date: "3-11-2017"
output: html_document
---

```
library("tidyr")
library("dplyr")
```

Step 2: Read data (and ignore warning messages)

```
ds1_s <- tbl_df(read.csv("data/CareCoordination/RawData-Part-1-5742477-11-2-2017-1509614063088.csv", skip = 2, colClasses = "character"))
ds2_s <- tbl_df(read.csv("data/CareCoordination/RawData-Part-2-5742477-11-2-2017-1509614068758.csv", skip = 2, colClasses = "character"))

```
Remove first line, because it contains subquestion headers
```
ds1_s <- ds1_s[-1,]
ds2_s <- ds2_s[-1,]

```

Concat all data

```
cc_staff <- rbind(ds1_s, ds2_s)
dim(cc_staff)
# [1] 5960  124
```

In total this dataframe has 5960 instances with 124 columns

/////

STEP 2: match Clinic Names and Clinic IDs from MOC file with those in LUT

First, Import Lookup Table file for matching with ccp file

```
LUT <- tbl_df(read.csv2("./data/LUT_v2.csv", sep=',', header=T, colClasses = "character"))


```
Add 'verwerkings code' column to moc file and initialize it with 'NM', which stands for 'non matching'.

```
cc_staff$verw_code <- "NM"

```

Match Clinic Name (lowercase) in moc file with clinic name in LUT file

```
c_name.idx <- match(tolower(cc_staff$Custom.Variable.5), tolower(LUT$c_name), nomatch=0)
c_name2.idx <- match(tolower(cc_staff$Custom.Variable.5), tolower(LUT$c_name2), nomatch=0) 
c_name3.idx <- match(tolower(cc_staff$Custom.Variable.5), tolower(LUT$c_name3), nomatch=0)

notnull_nm1 <- which(c_name.idx !=0)
notnull_nm2 <- which(c_name2.idx > 1) # skip also 1, which matches to ''
notnull_nm3 <- which(c_name3.idx > 1) # skip also 1, which matches to ''


length(notnull_nm1)
#[1] 5087
length(notnull_nm2)
# [1] 754
length(notnull_nm3)
#[1] 10


```
Found in total 5087 matches on 'c_name' and 754 on 'c_name2' and 10 on c_name3 in column `Custom Variable 5`. These have to be substituted by those in LUT. For this matches, the verwerkings code will be changed into 'VCNM'

``` 
cc_staff$country[notnull_nm1] <- LUT$country[c_name.idx]
cc_staff$clinic[notnull_nm1] <- LUT$c_name[c_name.idx]
cc_staff$clinic_id[notnull_nm1] <- LUT$c_id[c_name.idx]
cc_staff$verw_code[notnull_nm1] <- "VCNM"


cc_staff$country[notnull_nm2] <- LUT$country[c_name2.idx[notnull_nm2]]
cc_staff$clinic[notnull_nm2] <- LUT$c_name[c_name2.idx[notnull_nm2]]
cc_staff$clinic_id[notnull_nm2] <- LUT$c_id[c_name2.idx[notnull_nm2]]
cc_staff$verw_code[notnull_nm2] <- "VCNM2"

cc_staff$country[notnull_nm3] <- LUT$country[c_name3.idx[notnull_nm3]]
cc_staff$clinic[notnull_nm3] <- LUT$c_name[c_name3.idx[notnull_nm3]]
cc_staff$clinic_id[notnull_nm3] <- LUT$c_id[c_name3.idx[notnull_nm3]]
cc_staff$verw_code[notnull_nm3] <- "VCNM3"

```

```
length(which(cc_staff$verw_code == 'NM'))
nm_staff <- cc_staff[which(cc_staff$verw_code == 'NM'),]
[1] 211

cc_staff$verw_code <- as.factor(cc_staff$verw_code)
cc_staff$Custom.Variable.4 <- as.factor(cc_staff$Custom.Variable.4)
table(cc_staff$Custom.Variable.4, cc_staff$verw_code)
```


At the end there are 211 instances with code 'NM'

Save files with and without verwerkingscode
```
write.csv(cc_staff[,1:124], file = "data/CareCoordination/Clean-5742477-11-2-2017_v2.csv")
write.csv(cc_staff, file = "data/CareCoordination/Clean-5742477-11-2-2017-verwerkingcode_v2.csv")

```










