---
title: "Clean MOC Data 2017"
author: "Esther Lips"
date: "3-12-2017"
output: html_document
---

This markdown file describes the cleaning of the MOC file.

Input files: raw data from QuestionPro (me thinks), LUT file


## Load packages
```{r message=FALSE}
library("tidyr")
library("dplyr")
rm(list=ls())
```

## Read in data

```{r Read data}
moc1 <- tbl_df(read.csv("data/RawData-MOC-11-13-2017/RawData-Part-1-5742959-11-13-2017-1510643476144.csv", skip = 2 , colClasses = "character"))
moc2 <- tbl_df(read.csv("data/RawData-MOC-11-13-2017/RawData-Part-2-5742959-11-13-2017-1510643516992.csv", skip = 2, colClasses = "character"))
head <- read.table('data/RawData-MOC-11-13-2017/RawData-Part-1-5742959-11-13-2017-1510643476144.csv', nrows = 2, header = FALSE, sep =',', stringsAsFactors = FALSE)

# read LUT
LUT <- tbl_df(read.csv2("./data/LUT_v2.csv", sep=',', header=T, colClasses = "character"))

# rbind data to single object
moc_raw <- rbind(moc1, moc2)
#dim(moc_raw)

print(paste("In total this file has", nrow(moc_raw),"responses."))

# For further purposes, add column 'verw_code', and initialize it with 'NM' (which stands for 'Non-Matching')
moc_raw$verw_code <- "NM"

```

## Convert 2017 data to 2016 scale

```{r Convert data to different scale}
# convert data 2017 to 2016 scales
for(q in 27:38)
{
    moc_raw[which(moc_raw[,q] == 1),q] <- 0
    moc_raw[which(moc_raw[,q] == 2),q] <- 1.25
    moc_raw[which(moc_raw[,q] == 3),q] <- 2.5
    moc_raw[which(moc_raw[,q] == 4),q] <- 3.75
    moc_raw[which(moc_raw[,q] == 5),q] <- 5
    #print(unique(moc_raw[,q]))
}
```

Match Clinic Name (lowercase) in moc_raw file with clinic name in LUT file

```{r Match Clinic Names}

# match clinic names from DataFile to clinic names in LUT file
c_name.idx <- match(tolower(moc_raw$Custom.Variable.5), tolower(LUT$c_name), nomatch=0)
c_name2.idx <- match(tolower(moc_raw$Custom.Variable.5), tolower(LUT$c_name2), nomatch=0) 
c_name3.idx <- match(tolower(moc_raw$Custom.Variable.5), tolower(LUT$c_name3), nomatch=0)

notnull_nm1 <- which(c_name.idx !=0)
notnull_nm2 <- which(c_name2.idx > 1) # skip also 1, which matches to ''
notnull_nm3 <- which(c_name3.idx > 1) # skip also 1, which matches to ''

nr_names = length(notnull_nm1)+length(notnull_nm2)+length(notnull_nm3)

print(paste("In total",nr_names,"matches on ClinicNames are found."))

```

```{r Correct ClinicName}
moc_raw$Custom.Variable.4[notnull_nm1] <- LUT$country[c_name.idx]
moc_raw$Custom.Variable.5[notnull_nm1] <- LUT$c_name[c_name.idx]
moc_raw$Custom.Variable.6[notnull_nm1] <- LUT$c_id[c_name.idx]
moc_raw$verw_code[notnull_nm1] <- "VCNM"


moc_raw$Custom.Variable.4[notnull_nm2] <- LUT$country[c_name2.idx[notnull_nm2]]
moc_raw$Custom.Variable.5[notnull_nm2] <- LUT$c_name[c_name2.idx[notnull_nm2]]
moc_raw$Custom.Variable.6[notnull_nm2] <- LUT$c_id[c_name2.idx[notnull_nm2]]
moc_raw$verw_code[notnull_nm2] <- "VCNM"

moc_raw$Custom.Variable.4[notnull_nm3] <- LUT$country[c_name3.idx[notnull_nm3]]
moc_raw$Custom.Variable.5[notnull_nm3] <- LUT$c_name[c_name3.idx[notnull_nm3]]
moc_raw$Custom.Variable.6[notnull_nm3] <- LUT$c_id[c_name3.idx[notnull_nm3]]
moc_raw$verw_code[notnull_nm3] <- "VCNM"

print(paste("The matches on ClinicNames are now corrected in Raw Data."))

```
## View matches in table

```{r view Matches}

#nm_moc <- moc_raw[which(moc_raw$verw_code == 'NM'),]

#length(which(moc_raw$verw_code == 'NM'))
# 0
#length(which(moc_raw$verw_code == 'VCID'))
#[1] 0
#length(which(moc_raw$verw_code == 'VCIP'))
#[1] 0
#length(which(moc_raw$verw_code == 'VCNM'))
# [1] 7586

moc_raw$verw_code <- as.factor(moc_raw$verw_code)
moc_raw$Custom.Variable.4 <- as.factor(moc_raw$Custom.Variable.4)
table <- table(moc_raw$Custom.Variable.4, moc_raw$verw_code)

table
```


## Update ClinicNames with short names (14 nov 2017)

```{r Change long clinicNames}
update_names <- tbl_df(read.csv2("./data/LUT_v3.csv", sep=',', header=T, colClasses = "character"))

c.idx <- match(moc_raw$Custom.Variable.6, update_names$c_id, nomatch=0)
notnull <- which(c.idx != 0)

df <- data.frame(matrix(ncol = 4, nrow = length(notnull)))
df[,1] <- moc_raw$Custom.Variable.5[notnull]
df[,2] <- moc_raw$Custom.Variable.6[notnull]
df[,3] <- update_names$c_id[c.idx]
df[,4] <- update_names$c_name[c.idx]

#test <- update_names$c_name[c.idx]
#test_lut <- moc_raw$Custom.Variable.5[notnull]

moc_raw$Custom.Variable.5[notnull] <- update_names$c_name[c.idx]

print(paste("Long clinicNames are now substituted by short ClinicNames."))

```

## Save files with and without verwerkingscode
```{r save clean data file for Qlik}

# make header
header <- mat.or.vec(nrow(head), ncol(moc_raw)+1)
header <- cbind(head, header)
header <- rbind(header, names(moc_raw))
header[1,which(header[1,] == 0)] <- ''
header[2,which(header[2,] == 0)] <- ''
header <- header[,1:42]

moc_raw <- moc_raw[which(moc_raw$verw_code != 'NM'),]

write.table(header[,1:41], file = "data/FINAL/MOC/Clean-5742959-11-14-2017.csv", row.names=F, col.names=F,fileEncoding = "UTF-8",sep=',')
write.table(moc_raw[,1:41], file = "data/FINAL/MOC/Clean-5742959-11-14-2017.csv", row.names=F, col.names=F, fileEncoding = "UTF-8", sep=',',append=TRUE)

write.table(header, file = "data/FINAL/MOC/Clean-5742959-11-14-2017-verwerkingcode.csv", row.names=F, col.names=F,fileEncoding = "UTF-8", sep=',')
write.table(moc_raw, file = "data/FINAL/MOC/Clean-5742959-11-14-2017-verwerkingcode.csv", row.names=F,col.names=F, sep=',',fileEncoding = "UTF-8", append=TRUE)

print(paste("Saved Qlik file as: data/FINAL/MOC/Clean-5742959-11-14-2017.csv"))
```


