---
title: "Calculate mean questionaires per country and clinic"
author: "Esther Lips"
date: "8-11-2017"
output: html_document
---

This document describes the steps taken to get the calculate the mean answers per question per month per country and clinic for MOC data

Load packages
```{r load packages}
library("tidyr")
library("dplyr")
rm(list=ls())
```

Read data
```{r Read data}
moc <- tbl_df(read.csv2("./data/FINAL/MOC/Clean-5742959-11-14-2017-verwerkingcode.csv", sep=',', header=T, colClasses = "character", skip=2))
moc <- moc[which(moc$Seq..Number == 1),]
#dim(moc)
# [1] 7586   43

LUT <- tbl_df(read.csv2("./data/LUT_v3.csv", sep=',', header=T, colClasses = "character"))
```

Get table per country
```{r table for countries}

# get unique countries & clinics 
un_countries <- unique(moc$Custom.Variable.4)
un_cids <- unique(moc$Custom.Variable.6)

#init country table
df1_q <- data.frame(matrix(ncol = 16, nrow = length(un_countries)))
colnames(df1_q) <- c("Country","reviews", "response rate", "score", paste("X", 1:12, sep=""))

#init clinic table
df2_q <- data.frame(matrix(ncol = 18, nrow = length(unique(moc$Custom.Variable.5))))
colnames(df2_q) <- c("Country","Clinic","Clinic_ID","reviews", "response rate", "score", paste("X", 1:12, sep=""))

i2 = 1 

for(i in 1:length(un_countries))
{
  country = un_countries[i]
  ix <- which(moc$Custom.Variable.4 == country)
  sub_data <- moc[ix,]
  
  un_cname <- unique(sub_data$Custom.Variable.6)
  
  c_lut <- LUT[which(LUT$country == country),]
  
  question_data <- cbind(sub_data[,11:13], sub_data[,27:38])
  
  mean_q <- colMeans(data.matrix(question_data[,4:15]), na.rm=T)
  mean_all <- mean(mean_q, na.rm=T)
  print(country)
  
  df1_q[i,1] <- country
  df1_q[i,2] <- nrow(sub_data)
  df1_q[i,3] <- round(nrow(sub_data)/sum(as.numeric(c_lut$NoE))*100, digits=4)
  df1_q[i,4] <- round(mean_all <- mean(mean_q, na.rm=T), digits=4)
  df1_q[i,5:16] <- round(colMeans(data.matrix(question_data[,4:15]),na.rm=T), digits=4)
  
  for(j in 1:length(un_cname))
  {
    c_idx <- which(question_data[,3] == un_cname[j])
    no_empl <- as.numeric(LUT$NoE[which(LUT$c_id == un_cname[j])])
    cl_data <- question_data[c_idx,]
    
    mean_q_cl <- colMeans(data.matrix(cl_data[,4:15]))
    mean_all_cl <- mean(mean_q_cl)
    
    df2_q[i2,1:3] <- cl_data[1,1:3]
    df2_q[i2,4] <- nrow(cl_data)
    df2_q[i2,5] <- round(nrow(cl_data)/no_empl*100, digits=4)
    df2_q[i2,6] <- round(mean(mean_q_cl), digits=4)
    df2_q[i2,7:18] <- round(colMeans(data.matrix(cl_data[,4:15])), digits=4)
    i2 = i2+1
  }
}

# sort df1 
df1_q <- df1_q[order(df1_q[,1]),]

arg <-  df2_q[which(df2_q[,1] == 'Argentina'),]
arg <- arg[order(arg[,2]),]

#write.csv(arg, file = "data/MOC_meanQuestionare_Argentina.csv" , row.names=F)

write.csv(df1_q, file = "data/MOC_meanScores_per_country_2017.csv" , row.names=F)
write.csv(df2_q, file = "data/MOC_meanScores_per_clinic_2017.csv" , row.names=F)
```