---
title: "Clean CareCoord_patients data"
author: "Esther Lips"
date: "3-11-2017"
output: html_document
---
This markdown file describes the cleaning of the Care coordinates Patients file.

STEP 0: load packages
```
library("tidyr")
library("dplyr")
```

STEP 1: Read in data

```
ps1 <- tbl_df(read.csv("data/PatientSatisfaction/RawData-Part-1-5783064-11-2-2017-1509612855955.csv", skip = 2, colClasses = "character"))
ps2 <- tbl_df(read.csv("data/PatientSatisfaction/RawData-Part-2-5783064-11-2-2017-1509612868323.csv", skip = 2, colClasses = "character"))
ps3 <- tbl_df(read.csv("data/PatientSatisfaction/RawData-Part-3-5783064-11-2-2017-1509612880053.csv", skip = 2, colClasses = "character"))
ps4 <- tbl_df(read.csv("data/PatientSatisfaction/RawData-Part-4-5783064-11-2-2017-1509612891744.csv", skip = 2, colClasses = "character"))
```


Concat all data

```

ps_data <- rbind(ps1, ps2, ps3, ps4)
dim(ps_data)
# [1] 19525    60
```
In total this file has 19525 instances with 60 columns

/////

STEP 2: match Clinic Names and Clinic IDs from PS file with those in LUT

First, Import Lookup Table file for matching with ccp file


```
LUT <- tbl_df(read.csv2("./data/LUT_v2.csv", sep=',', header=T, colClasses = "character"))

```

Add 'verwerkings code' column to moc file and initialize it with NM, which stands for non matching.

```
ps_data$verw_code <- "NM"

```

Match column ps_data with the different clinic_names in LUT
```
c_name.idx <- match(tolower(ps_data$clinic), tolower(LUT$c_name), nomatch=0)
c_name2.idx <- match(tolower(ps_data$clinic), tolower(LUT$c_name2), nomatch=0) 
c_name3.idx <- match(tolower(ps_data$clinic), tolower(LUT$c_name3), nomatch=0)

notnull_nm1 <- which(c_name.idx !=0)
notnull_nm2 <- which(c_name2.idx > 1) # skip also 1, which matches to ''
notnull_nm3 <- which(c_name3.idx > 1) # skip also 1, which matches to ''


length(notnull_nm1)
#[1] 13843
length(notnull_nm2)
# [1] 213
length(notnull_nm3)
#[1] 87


```

Found in total 13843 matches on 'c_name' and 213 on 'c_name2' and 87 on 'c_name3 'in column `ps_data$clinic`. These have to be substituted by 'c_name' in LUT. For this matches, the verwerkings code will be changed into 'VCNM'

``` 
ps_data$country[notnull_nm1] <- LUT$country[c_name.idx]
ps_data$clinic[notnull_nm1] <- LUT$c_name[c_name.idx]
ps_data$clinic_id[notnull_nm1] <- LUT$c_id[c_name.idx]
ps_data$verw_code[notnull_nm1] <- "VCNM"

ps_data$country[notnull_nm2] <- LUT$country[c_name2.idx[notnull_nm2]]
ps_data$clinic[notnull_nm2] <- LUT$c_name[c_name2.idx[notnull_nm2]]
ps_data$clinic_id[notnull_nm2] <- LUT$c_id[c_name2.idx[notnull_nm2]]
ps_data$verw_code[notnull_nm2] <- "VCNM2"

ps_data$country[notnull_nm3] <- LUT$country[c_name3.idx[notnull_nm3]]
ps_data$clinic[notnull_nm3] <- LUT$c_name[c_name3.idx[notnull_nm3]]
ps_data$clinic_id[notnull_nm3] <- LUT$c_id[c_name3.idx[notnull_nm3]]
ps_data$verw_code[notnull_nm3] <- "VCNM3"


```

Check whether the instances that could not be matched on clinic names can be matched on clinic_id
```

length(which(ps_data$verw_code == 'NM'))
#[1] 5540
nm.idx <- which(ps_data$verw_code == 'NM')
nm_ps <- ps_data[nm.idx,]
nm_ps$index <- nm.idx

# match clinic_id name on subset
cid1.idx <- match(nm_ps$clinic_id, LUT$c_id, nomatch=0)
notnull_c1 <- which(cid1.idx !=0)
length(notnull_c1)
# [1] 2934

cid2.idx <- match(nm_ps$clinic_id, LUT$c_id2, nomatch=0)
notnull_c2 <- which(cid2.idx > 1)
length(notnull_c2)
#[1] 70

```

Found in total 2934 matches on c_id and 70 on c_id2 and changed the 'country', 'clinic_id' and 'clinic' to those in the LUT file. Subsequently, I overwrite the same instances in the 'ps_data' (little complicated, but for double check if everything goes ok). 

```

nm_ps$country[notnull_c1] <- LUT$country[cid1.idx]
nm_ps$clinic[notnull_c1] <- LUT$c_name[cid1.idx]
nm_ps$clinic_id[notnull_c1] <- LUT$c_id[cid1.idx]
nm_ps$verw_code[notnull_c1] <- "VCID1"


nm_ps$country[notnull_c2] <- LUT$country[cid2.idx[notnull_c2]]
nm_ps$clinic[notnull_c2] <- LUT$c_name[cid2.idx[notnull_c2]]
nm_ps$clinic_id[notnull_c2] <- LUT$c_id[cid2.idx[notnull_c2]]
nm_ps$verw_code[notnull_c2] <- "VCID2"

sb.idx <- which(nm_ps$verw_code != 'NM')
ps_data[nm_ps$index[sb.idx], 8:10] <- nm_ps[sb.idx, 8:10]
ps_data[nm_ps$index[sb.idx], 61] <- nm_ps[sb.idx, 61]

```
REcheck 'NM' items and match op clinic_id

```
nm_ps2 <- ps_data[which(ps_data$verw_code == 'NM'),]
length(which(ps_data$verw_code == 'NM'))
# [1] 2536

ps_data$verw_code <- as.factor(ps_data$verw_code)
ps_data$country <- as.factor(ps_data$country)
table(ps_data$country, ps_data$verw_code)
```
Summarizing: there are in total 2536 items with verw_code 'NM' for which 2229 are completely empty in 'country'. Some other items have a country but no 'cid' or 'clinic_id'. 

Save files with and without verwerkingscode
```
write.csv(ccp_data[,1:60], file = "data/PatientSatisfaction/Clean-5742959-11-2-2017_v2.csv")
write.csv(ccp_data, file = "data/PatientSatisfaction/Clean-5742959-11-2-2017-verwerkingcode_v2.csv")

```