---
title: "Calculate mean questionaires per country and clinic"
author: "Esther Lips"
date: "9-11-2017"
output: html_document
---

This document describes the steps taken to get the calculate the mean answers per question per month per country and clinic. 

1) Read data & discard the responses with sequence ID > 1

```{r load packages}
rm(list=ls())
library("tidyr")
library("dplyr")
```

```{r Read data}
ps <- read.csv("./data/FINAL/PS/Clean-5783064-11-14-2017-verwerkingcode.csv", sep=',', header=T, colClasses = "character", skip=2)

LUT <- tbl_df(read.csv("./data/LUT_v3.csv", sep=',', header=T, colClasses = "character"))

#dim(ps)
# [1]  20295   62

```
Get table for countries/global for 'All PatientTypes'

```{r Country data 'All Patients'}

# get unique countries & clinics 
un_countries <- unique(ps$country)
un_cids <- unique(ps$clinic_id)

#init country table
df1_q <- data.frame(matrix(ncol = 14, nrow = length(un_countries)))
colnames(df1_q) <- c("Country","reviews", "response rate","mean score", c(paste("X1.", 1:9, sep="")),"rowMean")

#init clinic table
df2_q <- data.frame(matrix(ncol = 16, nrow = length(un_cids)))
colnames(df2_q) <- c("Country","Clinic_ID","Clinic","reviews", "response rate", "mean score", c(paste("X1.", 1:9, sep="")), "rowMean")

i2 = 1 

for(i in 1:length(un_countries))
{
  country = un_countries[i]
  ix <- which(ps$country == country)
  sub_data <- ps[ix,]

  un_cname <- unique(sub_data$clinic_id)
  
  c_lut <- LUT[which(LUT$country == country),]
  
  q1_data <- c(sub_data[,36], sub_data[,43], sub_data[,50])
  q2_data <- c(sub_data[,37], sub_data[,44], sub_data[,51])
  q3_data <- c(sub_data[,38], sub_data[,45])
  q4_data <- c(sub_data[,39])
  q5_data <- c(sub_data[,40], sub_data[,47])
  q6_data <- c(sub_data[,41], sub_data[,48], sub_data[,55])
  q7_data <- c(sub_data[,46], sub_data[,53])
  q8_data <- c(sub_data[,52])
  q9_data <- c(sub_data[,54])
  rowMean_data <- c(sub_data[,61])
  
  print(country)
  
  df1_q[i,1] <- sub_data[1,8]
  df1_q[i,2] <- nrow(sub_data)
  df1_q[i,3] <- round(nrow(sub_data)/sum(as.numeric(c_lut$NoP), na.rm=TRUE)*100, digits=4)
  df1_q[i,5] <- round(mean(as.numeric(q1_data)-1, na.rm=T)*10, digits=4)
  df1_q[i,6] <- round(mean(as.numeric(q2_data)-1, na.rm=T)*10, digits=4)
  df1_q[i,7] <- round(mean(as.numeric(q3_data)-1, na.rm=T)*10, digits=4)
  df1_q[i,8] <- round(mean(as.numeric(q4_data)-1, na.rm=T)*10, digits=4)
  df1_q[i,9] <- round(mean(as.numeric(q5_data)-1, na.rm=T)*10, digits=4)
  df1_q[i,10] <- round(mean(as.numeric(q6_data)-1, na.rm=T)*10, digits=4)
  df1_q[i,11] <- round(mean(as.numeric(q7_data)-1, na.rm=T)*10, digits=4)
  df1_q[i,12] <- round(mean(as.numeric(q8_data)-1, na.rm=T)*10, digits=4)
  df1_q[i,13] <- round(mean(as.numeric(q9_data)-1, na.rm=T)*10, digits=4)
  df1_q[i,14] <- round(mean(as.numeric(rowMean_data)-1, na.rm=T)*10, digits=4)
  df1_q[i,4] <- round(mean(as.numeric(df1_q[i,5:13])), digits=4)
  
  for(j in 1:length(un_cname))
  {
    #print(un_cname[j])
    c_idx <- which(sub_data$clinic_id == un_cname[j])
    no_empl <- as.numeric(LUT$NoP[which(LUT$c_id == un_cname[j])])
    cl_data <- sub_data[c_idx,]
    
    q1_data_cl <- c(cl_data[,36], cl_data[,43], cl_data[,50])
    q2_data_cl <- c(cl_data[,37], cl_data[,44], cl_data[,51])
    q3_data_cl <- c(cl_data[,38], cl_data[,45])
    q4_data_cl <- c(cl_data[,39])
    q5_data_cl <- c(cl_data[,40], cl_data[,47])
    q6_data_cl <- c(cl_data[,41], cl_data[,48], cl_data[,55])
    q7_data_cl <- c(cl_data[,46], cl_data[,53])
    q8_data_cl <- c(cl_data[,52])
    q9_data_cl <- c(cl_data[,54])
    rowMean_data_cl <- c(cl_data[,61])
    
    #mean_q_cl <- colMeans(data.matrix(cl_data[,4:21]),na.rm=TRUE)
    #mean_all_cl <- mean(mean_q_cl,na.rm=TRUE)
    
    df2_q[i2,1:3] <- cl_data[1,8:10]
    df2_q[i2,4] <- nrow(cl_data)
    df2_q[i2,5] <- round(nrow(cl_data)/sum(as.numeric(no_empl), na.rm=TRUE)*100, digits=4)
    df2_q[i2,7] <- round(mean(as.numeric(q1_data_cl)-1, na.rm=T)*10, digits=4)
    df2_q[i2,8] <- round(mean(as.numeric(q2_data_cl)-1, na.rm=T)*10, digits=4)
    df2_q[i2,9] <- round(mean(as.numeric(q3_data_cl)-1, na.rm=T)*10, digits=4)
    df2_q[i2,10] <- round(mean(as.numeric(q4_data_cl)-1, na.rm=T)*10, digits=4)
    df2_q[i2,11] <- round(mean(as.numeric(q5_data_cl)-1, na.rm=T)*10, digits=4)
    df2_q[i2,12] <- round(mean(as.numeric(q6_data_cl)-1, na.rm=T)*10, digits=4)
    df2_q[i2,13] <- round(mean(as.numeric(q7_data_cl)-1, na.rm=T)*10, digits=4)
    df2_q[i2,14] <- round(mean(as.numeric(q8_data_cl)-1, na.rm=T)*10, digits=4)
    df2_q[i2,15] <- round(mean(as.numeric(q9_data_cl)-1, na.rm=T)*10, digits=4)
    df2_q[i2,16] <- round(mean(as.numeric(rowMean_data_cl)-1, na.rm=T)*10, digits=4)
    df2_q[i2,6] <- round(mean(as.numeric(df2_q[i2,7:15]), na.rm=T), digits=4)

    i2 = i2+1
  }
}

write.csv(df1_q, file = "data/PS_meanScores_per_country_2017.csv" , row.names=F )
write.csv(df2_q, file = "data/PS_meanScores_per_clinic_2017.csv" , row.names=F )

```
Get table per patienttype
```{r table per PatientType}

# get unique countries & clinics 
un_countries <- unique(ps$country)
un_cids <- unique(ps$clinic_id)
un_patient_types <- unique(ps$patient_type)

for(p in 1:length(un_patient_types))
{
  ix <- which(ps$patient_type == un_patient_types[p])
  patient_data <- ps[ix,]
  
  ptype <- c("PatientType_HD", "PatientType_HomeHD_PD", "PatientType_Clinic_Consult") # for filenames
  un_cids <- unique(patient_data$clinic_id)
  
  #init country table
  df1_q <- data.frame(matrix(ncol = 14, nrow = length(un_countries)))
  colnames(df1_q) <- c("Country","reviews", "response rate","mean score", c(paste("X1.", 1:9, sep="")),"rowMean")
  
  #init clinic table
  df2_q <- data.frame(matrix(ncol = 16, nrow = length(un_cids)))
  colnames(df2_q) <- c("Country","Clinic_ID","Clinic","reviews", "response rate", "mean score", c(paste("X1.", 1:9, sep="")), "rowMean")
  
  i2 = 1 
  
  for(i in 1:length(un_countries))
  {
    country = un_countries[i]
    ix <- which(patient_data$country == country)
    sub_data <- patient_data[ix,]
  
    un_cname <- unique(sub_data$clinic_id)
    
    c_lut <- LUT[which(LUT$country == country),]
    
    if(nrow(sub_data) == 0)
    {
      df1_q[i,1] <- country
      df1_q[i,2] <- 0
    }
    
    if(nrow(sub_data) != 0)
    {
      q1_data <- c(sub_data[,36], sub_data[,43], sub_data[,50])
      q2_data <- c(sub_data[,37], sub_data[,44], sub_data[,51])
      q3_data <- c(sub_data[,38], sub_data[,45])
      q4_data <- c(sub_data[,39])
      q5_data <- c(sub_data[,40], sub_data[,47])
      q6_data <- c(sub_data[,41], sub_data[,48], sub_data[,55])
      q7_data <- c(sub_data[,46], sub_data[,53])
      q8_data <- c(sub_data[,52])
      q9_data <- c(sub_data[,54])
      rowMean_data <- c(sub_data[,61])
      
      #print(country)
      
      df1_q[i,1] <- sub_data[1,8]
      df1_q[i,2] <- nrow(sub_data)
      df1_q[i,3] <- round(nrow(sub_data)/sum(as.numeric(c_lut$NoP), na.rm=TRUE)*100, digits=4)
      df1_q[i,5] <- round(mean(as.numeric(q1_data)-1, na.rm=T)*10, digits=4)
      df1_q[i,6] <- round(mean(as.numeric(q2_data)-1, na.rm=T)*10, digits=4)
      df1_q[i,7] <- round(mean(as.numeric(q3_data)-1, na.rm=T)*10, digits=4)
      df1_q[i,8] <- round(mean(as.numeric(q4_data)-1, na.rm=T)*10, digits=4)
      df1_q[i,9] <- round(mean(as.numeric(q5_data)-1, na.rm=T)*10, digits=4)
      df1_q[i,10] <- round(mean(as.numeric(q6_data)-1, na.rm=T)*10, digits=4)
      df1_q[i,11] <- round(mean(as.numeric(q7_data)-1, na.rm=T)*10, digits=4)
      df1_q[i,12] <- round(mean(as.numeric(q8_data)-1, na.rm=T)*10, digits=4)
      df1_q[i,13] <- round(mean(as.numeric(q9_data)-1, na.rm=T)*10, digits=4)
      df1_q[i,14] <- round(mean(as.numeric(rowMean_data)-1, na.rm=T)*10, digits=4)
      df1_q[i,4] <- round(mean(as.numeric(df1_q[i,5:13])), digits=4)
      
      for(j in 1:length(un_cname))
      {
        #print(paste(un_cname[j], nrow(cl_data)))
        c_idx <- which(sub_data$clinic_id == un_cname[j])
        no_empl <- as.numeric(LUT$NoP[which(LUT$c_id == un_cname[j])])
        cl_data <- sub_data[c_idx,]
        
        #print(nrow(cl_data))
        if(nrow(cl_data) == 0)
        {
          df2_q[i2,1] <- country
          df2_q[i2,2] <- un_cname[j]
          df2_q[i2,4] <- 0
        }
        
        if(nrow(cl_data) != 0)
        {
          q1_data_cl <- c(cl_data[,36], cl_data[,43], cl_data[,50])
          q2_data_cl <- c(cl_data[,37], cl_data[,44], cl_data[,51])
          q3_data_cl <- c(cl_data[,38], cl_data[,45])
          q4_data_cl <- c(cl_data[,39])
          q5_data_cl <- c(cl_data[,40], cl_data[,47])
          q6_data_cl <- c(cl_data[,41], cl_data[,48], cl_data[,55])
          q7_data_cl <- c(cl_data[,46], cl_data[,53])
          q8_data_cl <- c(cl_data[,52])
          q9_data_cl <- c(cl_data[,54])
          rowMean_data_cl <- c(cl_data[,61])
          
          #mean_q_cl <- colMeans(data.matrix(cl_data[,4:21]),na.rm=TRUE)
          #mean_all_cl <- mean(mean_q_cl,na.rm=TRUE)
          
          df2_q[i2,1:3] <- cl_data[1,8:10]
          df2_q[i2,4] <- nrow(cl_data)
          df2_q[i2,5] <- round(nrow(cl_data)/sum(as.numeric(no_empl), na.rm=TRUE)*100, digits=4)
          df2_q[i2,7] <- round(mean(as.numeric(q1_data_cl)-1, na.rm=T)*10, digits=4)
          df2_q[i2,8] <- round(mean(as.numeric(q2_data_cl)-1, na.rm=T)*10, digits=4)
          df2_q[i2,9] <- round(mean(as.numeric(q3_data_cl)-1, na.rm=T)*10, digits=4)
          df2_q[i2,10] <- round(mean(as.numeric(q4_data_cl)-1, na.rm=T)*10, digits=4)
          df2_q[i2,11] <- round(mean(as.numeric(q5_data_cl)-1, na.rm=T)*10, digits=4)
          df2_q[i2,12] <- round(mean(as.numeric(q6_data_cl)-1, na.rm=T)*10, digits=4)
          df2_q[i2,13] <- round(mean(as.numeric(q7_data_cl)-1, na.rm=T)*10, digits=4)
          df2_q[i2,14] <- round(mean(as.numeric(q8_data_cl)-1, na.rm=T)*10, digits=4)
          df2_q[i2,15] <- round(mean(as.numeric(q9_data_cl)-1, na.rm=T)*10, digits=4)
          df2_q[i2,16] <- round(mean(as.numeric(rowMean_data_cl)-1, na.rm=T)*10, digits=4)
          df2_q[i2,6] <- round(mean(as.numeric(df2_q[i2,7:15]), na.rm=T), digits=4)
      
          i2 = i2+1
        }
      }
    }
  }
  
  write.csv(df1_q, file = paste("data/PS_meanScores_",ptype[p],"_countries_2017.csv",sep='') , row.names=F )
  write.csv(df2_q, file = paste("data/PS_meanScores_",ptype[p],"_clinics_2017.csv",sep=''), row.names=F )
}

```

